### ISSUE TITLE
JsonArray request payload fails to parse

### ISSUE THREAD

**Issue by spaisey** [mindprogenitor/wiremock-freemarker-extension#1]
Should a request payload represent an array, the request fails to be parsed and causes a runtime exception. For example:

```
[
    {
        "idType": "ID_ISIN",
        "includeUnlistedEquities": true,
        "idValue": "US01609W1027"
    },
    {
        "idType": "ID_ISIN",
        "includeUnlistedEquities": true,
        "idValue": "CH0244767585"
    }
]
```
The issue is that the any request Json is expected to parse as a Map:

```
    private Map parseJson(String request) throws IOException {
        return jsonMapper.readValue(request, Map.class);
    }
```

Suggest checking for initial `[`character and parsing accordingly. 
Will fix and raise PR.

**Comment by mindprogenitor** [comment]
Thanks Spaisey. as commented on the pr, due to personal matters I have been absent for quite a long time (was even unaware of anyone else using this). Thanks for the fix.
